name: Test by manual

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        default: "Target URL"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        cache-dependency-path: setup.cfg
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -e .[dev]
    - run: getjump --version
    - run: getjump -f "${{ github.event.inputs.url }}"
